package fr.insa.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2020-04-09T01:00:10.567-07:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "ProductOrderingServiceService", 
                  wsdlLocation = "file:/home/azerty/eclipse-workspace/cfx-app-client/src/main/resources/wsdl/ProductOrderingService.wsdl",
                  targetNamespace = "http://service.insa.fr/") 
public class ProductOrderingServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.insa.fr/", "ProductOrderingServiceService");
    public final static QName ProductOrderingServicePort = new QName("http://service.insa.fr/", "ProductOrderingServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/azerty/eclipse-workspace/cfx-app-client/src/main/resources/wsdl/ProductOrderingService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProductOrderingServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/azerty/eclipse-workspace/cfx-app-client/src/main/resources/wsdl/ProductOrderingService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProductOrderingServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProductOrderingServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductOrderingServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProductOrderingServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProductOrderingServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProductOrderingServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ProductOrderingService
     */
    @WebEndpoint(name = "ProductOrderingServicePort")
    public ProductOrderingService getProductOrderingServicePort() {
        return super.getPort(ProductOrderingServicePort, ProductOrderingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductOrderingService
     */
    @WebEndpoint(name = "ProductOrderingServicePort")
    public ProductOrderingService getProductOrderingServicePort(WebServiceFeature... features) {
        return super.getPort(ProductOrderingServicePort, ProductOrderingService.class, features);
    }

}
